import {InMemoryDbService} from 'angular-in-memory-web-api';

export class AppInMemoryApi implements InMemoryDbService {
  createDb() {
    return {
      carros: [
        {
          id:1,
          titulo: 'Fiat Uno Way 1.0 Economy 2012',
          descricao: ' Sem entrada',
          placaDoCarro: 'a',
          marca:'Fiat',
          modelo:'Uno',
          anoDoModelo:'2012',
          versao:'1.0',
          cambio:'Manual',
          combustivel:'a',
          direcao:'a',
          potenciaDoMotor:'a',
          tipoDeVeiculo: 'a',
          quilometragem: 89000,
          portas: 4,
          finalDaPlaca: 1,
          cor:'Branco',
          airBag: false,
          alarme: false,
          arCondicionado: false,
          travaEletrica: false,
          vidroEletrico: false,
          som: false,
          sensorRe: false,
          cameraRe: false,
          blindado: false,
          direcaoHidraulica: false,
          aceitaTrocas: false,
          unicoDono: false,
          preco: 1790000,
          image: 'unoBranco.jpg',
          estadoFinanceiro: 1,
          cep: 'a',
        },
        {
          id: 2,
          titulo: 'Fiat Uno Way 1.0 Economy 2012',
          descricao: ' Sem entrada',
          placaDoCarro: 'a',
          marca:'Fiat',
          modelo:'Uno',
          anoDoModelo:'2012',
          versao:'1.0',
          cambio:'Manual',
          combustivel:'a',
          direcao:'a',
          potenciaDoMotor:'a',
          tipoDeVeiculo: 'a',
          quilometragem: 89000,
          portas: 4,
          finalDaPlaca: 1,
          cor:'Branco',
          airBag: false,
          alarme: false,
          arCondicionado: false,
          travaEletrica: false,
          vidroEletrico: false,
          som: false,
          sensorRe: false,
          cameraRe: false,
          blindado: false,
          direcaoHidraulica: false,
          aceitaTrocas: false,
          unicoDono: false,
          preco: 1790000,
          image: 'unoBranco.jpg',
          estadoFinanceiro: 1,
          cep: 'a',
        },
        {
          id: 3,
          titulo: 'Fiat Uno Way 1.0 Economy 2012',
          descricao: ' Sem entrada',
          placaDoCarro: 'a',
          marca:'Fiat',
          modelo:'Uno',
          anoDoModelo:'2012',
          versao:'1.0',
          cambio:'Manual',
          combustivel:'a',
          direcao:'a',
          potenciaDoMotor:'a',
          tipoDeVeiculo: 'a',
          quilometragem: 89000,
          portas: 4,
          finalDaPlaca: 1,
          cor:'Branco',
          airBag: false,
          alarme: false,
          arCondicionado: false,
          travaEletrica: false,
          vidroEletrico: false,
          som: false,
          sensorRe: false,
          cameraRe: false,
          blindado: false,
          direcaoHidraulica: false,
          aceitaTrocas: false,
          unicoDono: false,
          preco: 1790000,
          image: 'unoBranco.jpg',
          estadoFinanceiro: 1,
          cep: 'a',
        },
        {
          id: 4,
          titulo: 'Fiat Uno Way 1.0 Economy 2012',
          descricao: ' Sem entrada',
          placaDoCarro: 'a',
          marca:'Fiat',
          modelo:'Uno',
          anoDoModelo:'2012',
          versao:'1.0',
          cambio:'Manual',
          combustivel:'a',
          direcao:'a',
          potenciaDoMotor:'a',
          tipoDeVeiculo: 'a',
          quilometragem: 89000,
          portas: 4,
          finalDaPlaca: 1,
          cor:'Branco',
          airBag: false,
          alarme: false,
          arCondicionado: false,
          travaEletrica: false,
          vidroEletrico: false,
          som: false,
          sensorRe: false,
          cameraRe: false,
          blindado: false,
          direcaoHidraulica: false,
          aceitaTrocas: false,
          unicoDono: false,
          preco: 1790000,
          image: 'unoBranco.jpg',
          estadoFinanceiro: 1,
          cep: 'a',
        },
        {
          id: 5,
          titulo: 'Fiat Uno Way 1.0 Economy 2012',
          descricao: ' Sem entrada',
          placaDoCarro: 'a',
          marca:'Fiat',
          modelo:'Uno',
          anoDoModelo:'2012',
          versao:'1.0',
          cambio:'Manual',
          combustivel:'a',
          direcao:'a',
          potenciaDoMotor:'a',
          tipoDeVeiculo: 'a',
          quilometragem: 89000,
          portas: 4,
          finalDaPlaca: 1,
          cor:'Branco',
          airBag: false,
          alarme: false,
          arCondicionado: false,
          travaEletrica: false,
          vidroEletrico: false,
          som: false,
          sensorRe: false,
          cameraRe: false,
          blindado: false,
          direcaoHidraulica: false,
          aceitaTrocas: false,
          unicoDono: false,
          preco: 1790000,
          image: 'unoBranco.jpg',
          estadoFinanceiro: 1,
          cep: 'a',
        },
      ],
      // platforms: [
      //   {
      //     id: 1,
      //     name: 'Xbox One'
      //   },
      //   {
      //     id: 2,
      //     name: 'PlayStation 4'
      //   },
      //   {
      //     id: 3,
      //     name: 'PC'
      //   }
      // ]
    };
  }
}
